// Generated by CoffeeScript PHP 1.3.1
(function() {

  $(function() {
    $("body").delegate('#js-scroll-top', 'click', function(event) {
      event.preventDefault();
      event.stopPropagation();
      return $('html, body').animate({
        scrollTop: 0
      }, "slow");
    });
    $('.js_datepicker').datepicker($.extend($.datepicker.regional['fr'], {
      showOn: 'button',
      buttonImage: '/images/calendar.gif',
      buttonImageOnly: true
    }));
    $("body").delegate(".js_confirm", 'click', function(event) {
      return window.confirm($(event.currentTarget).data("confirm"));
    });
    $("body").delegate('.readMore', 'click', function(event) {
      $('.collapsable').toggleClass('open', 100);
      $('.readMore').replaceWith('<a href="#" class="readLess">masquer</a>');
      return false;
    });
    $("body").delegate('.readLess', 'click', function(event) {
      $('.collapsable').toggleClass('open', 100);
      $('.readLess').replaceWith('<a href="#" class="readMore">lire la suite</a>');
      return false;
    });
    $('[data-title]').tooltip({
      "content": function() {
        return $(this).attr('data-title');
      }
    });
    $('input, textarea').placeholder();
    $("#devis").hide();
    $("#devis_toggle").click(function(event) {
      event.preventDefault();
      event.stopPropagation();
      return $("#devis").toggle();
    });
    return $("#confirm_annulation").click(function(event) {
      event.preventDefault();
      event.stopPropagation();
      return $("#annulation-modal").dialog({
        dialogClass: "no-close",
        resizable: false,
        height: 250,
        width: 350,
        modal: true,
        buttons: {
          "non": function() {
            return $(this).dialog("close");
          },
          "oui, annuler la consultation": function() {
            $(this).dialog("close");
            return window.location.href = event.target.href;
          }
        }
      });
    });
  });

}).call(this);

// Generated by CoffeeScript PHP 1.3.1
(function() {

  $(function() {
    var initCategories;
    $(".js_categories").delegate("select", "change", function(event) {
      $.post($(".js_categories").data("url"), $(".js_categories select").serialize(), function(data) {
        $(".js_categories").html(data);
        $("#inscription_organisme_form_categorieLevelTwo, #inscription_organisme_form_categorieLevelOne").unbind("change");
        return $("#inscription_organisme_form_categorieLevelTwo, #inscription_organisme_form_categorieLevelOne").bind("change", function() {
          return initCategories();
        });
      });
      return event.preventDefault();
    });
    initCategories = function() {
      if ($("#inscription_organisme_form_categorieLevelTwo option:selected").text() === "Association" && $("#inscription_organisme_form_categorieLevelOne option:selected").val() !== "") {
        $('#inscription_organisme_form_autreCategorie').parent().parent().hide();
        $("#inscription_organisme_form_rna").attr('required', 'required');
        $("#rna").show(1000);
        $("#inscription_organisme_form_siren").removeAttr('required');
        $("#inscription_organisme_form_siren").parent().parent().find(".required-flag").remove();
        $("#inscription_organisme_form_siren").parent().parent().hide(1000);
        $("#inscription_organisme_form_siret").parent().parent().hide(1000);
        if ($("#inscription_organisme_form_rna").parent().parent().find('.required-flag').length === 0) {
          $("#inscription_organisme_form_rna").parent().parent().find("label").append('<span class="required-flag">*</span>');
          return $("#rna").show(1000);
        } else {
          $("#inscription_organisme_form_rna").removeAttr('required', 'required');
          $("#inscription_organisme_form_rna").parent().parent().find(".required-flag").remove();
          $("#rna").hide(1000);
          $("#inscription_organisme_form_siren").attr('required', 'required');
          $("#inscription_organisme_form_siren").parent().parent().show(1000);
          if ($("#inscription_organisme_form_siren").parent().parent().find('.required-flag').length === 0) {
            $("#inscription_organisme_form_siren").parent().parent().find("label").append('<span class="required-flag">*</span>');
          }
          return $("#inscription_organisme_form_siret").parent().parent().show(1000);
        }
      } else if ($("#inscription_organisme_form_categorieLevelTwo option:selected").text() === "Autre" && $("#inscription_organisme_form_categorieLevelOne option:selected").val() !== "") {
        $("#inscription_organisme_form_rna").removeAttr('required', 'required');
        $("#inscription_organisme_form_rna").parent().parent().find(".required-flag").remove();
        $("#rna").hide(1000);
        $('#inscription_organisme_form_autreCategorie').parent().parent().show();
        if ($("#inscription_organisme_form_autreCategorie").parent().parent().find('.required-flag').length === 0) {
          $('#inscription_organisme_form_autreCategorie').parent().parent().find('label').append('<span class="required-flag">*</span>');
          return $('#inscription_organisme_form_autreCategorie input').attr('required', 'required');
        }
      } else {
        $('#inscription_organisme_form_autreCategorie').parent().parent().hide();
        $("#rna").hide(1000);
        $("#inscription_organisme_form_rna").removeAttr('required', 'required');
        $("#inscription_organisme_form_rna").parent().parent().find(".required-flag").remove();
        $("#inscription_organisme_form_siren").attr('required', 'required');
        $("#inscription_organisme_form_siren").parent().parent().show(1000);
        if ($("#inscription_organisme_form_siren").parent().parent().find('.required-flag').length === 0) {
          $("#inscription_organisme_form_siren").parent().parent().find("label").append('<span class="required-flag">*</span>');
        }
        return $("#inscription_organisme_form_siret").parent().parent().show(1000);
      }
    };
    return initCategories();
  });

}).call(this);
