default:
    extensions:
        Behat\Symfony2Extension\Extension:
            mink_driver: true
            kernel:
                env:   test
                debug: true
        Behat\MinkExtension\Extension:
            base_url:   "http://localhost:8000/app_test.php"
            goutte:
                guzzle_parameters:
                    curl.options:
                        CURLOPT_PORT: 8000
            selenium2:
                wd_host: "http://localhost:9876/wd/hub"
