parameters:
#    flair_prestataire.example.class: Flair\PrestataireBundle\Example

services:

#    flair_prestataire.example:
#        class: %flair_prestataire.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
