<?php

namespace Proxies\__CG__\Flair\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Consultation extends \Flair\CoreBundle\Entity\Consultation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'id', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'titre', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'description', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'categorie', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'dateLimite', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'prixMinimum', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'prixMaximum', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'periodeDebut', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'dateDebut', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'periodeLivraison', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'dateLivraison', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'experienceRequise', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'certificationRequise', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'certifications', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'organisme', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'statut', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'dateCreation', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'dateUpdate', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'documents', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'reponses', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'reponseSelectionne');
        }

        return array('__isInitialized__', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'id', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'titre', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'description', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'categorie', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'dateLimite', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'prixMinimum', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'prixMaximum', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'periodeDebut', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'dateDebut', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'periodeLivraison', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'dateLivraison', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'experienceRequise', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'certificationRequise', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'certifications', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'organisme', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'statut', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'dateCreation', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'dateUpdate', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'documents', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'reponses', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Consultation' . "\0" . 'reponseSelectionne');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Consultation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function onPreUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreUpdate', array());

        return parent::onPreUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function hasUnansweredQuestions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasUnansweredQuestions', array());

        return parent::hasUnansweredQuestions();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie($categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', array($categorie));

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', array());

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', array($dateCreation));

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', array());

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUpdate($dateUpdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUpdate', array($dateUpdate));

        return parent::setDateUpdate($dateUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUpdate', array());

        return parent::getDateUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganisme($organisme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganisme', array($organisme));

        return parent::setOrganisme($organisme);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganisme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganisme', array());

        return parent::getOrganisme();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixMaximum($prixMaximum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixMaximum', array($prixMaximum));

        return parent::setPrixMaximum($prixMaximum);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixMaximum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixMaximum', array());

        return parent::getPrixMaximum();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixMinimum($prixMinimum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixMinimum', array($prixMinimum));

        return parent::setPrixMinimum($prixMinimum);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixMinimum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixMinimum', array());

        return parent::getPrixMinimum();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', array($statut));

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', array());

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateLimite($dateLimite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateLimite', array($dateLimite));

        return parent::setDateLimite($dateLimite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateLimite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateLimite', array());

        return parent::getDateLimite();
    }

    /**
     * {@inheritDoc}
     */
    public function setCertificationRequise($certificationRequise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCertificationRequise', array($certificationRequise));

        return parent::setCertificationRequise($certificationRequise);
    }

    /**
     * {@inheritDoc}
     */
    public function getCertificationRequise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCertificationRequise', array());

        return parent::getCertificationRequise();
    }

    /**
     * {@inheritDoc}
     */
    public function setCertifications($certifications)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCertifications', array($certifications));

        return parent::setCertifications($certifications);
    }

    /**
     * {@inheritDoc}
     */
    public function getCertifications()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCertifications', array());

        return parent::getCertifications();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebut($dateDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebut', array($dateDebut));

        return parent::setDateDebut($dateDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebut', array());

        return parent::getDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateLivraison($dateLivraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateLivraison', array($dateLivraison));

        return parent::setDateLivraison($dateLivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateLivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateLivraison', array());

        return parent::getDateLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setExperienceRequise($experienceRequise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExperienceRequise', array($experienceRequise));

        return parent::setExperienceRequise($experienceRequise);
    }

    /**
     * {@inheritDoc}
     */
    public function getExperienceRequise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExperienceRequise', array());

        return parent::getExperienceRequise();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodeDebut($periodeDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodeDebut', array($periodeDebut));

        return parent::setPeriodeDebut($periodeDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodeDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodeDebut', array());

        return parent::getPeriodeDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodeLivraison($periodeLivraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodeLivraison', array($periodeLivraison));

        return parent::setPeriodeLivraison($periodeLivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodeLivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodeLivraison', array());

        return parent::getPeriodeLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocuments($documents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocuments', array($documents));

        return parent::setDocuments($documents);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocuments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocuments', array());

        return parent::getDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function setReponses($reponses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReponses', array($reponses));

        return parent::setReponses($reponses);
    }

    /**
     * {@inheritDoc}
     */
    public function getReponses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReponses', array());

        return parent::getReponses();
    }

    /**
     * {@inheritDoc}
     */
    public function setReponseSelectionne($reponseSelectionne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReponseSelectionne', array($reponseSelectionne));

        return parent::setReponseSelectionne($reponseSelectionne);
    }

    /**
     * {@inheritDoc}
     */
    public function getReponseSelectionne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReponseSelectionne', array());

        return parent::getReponseSelectionne();
    }

    /**
     * {@inheritDoc}
     */
    public function getStringStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStringStatus', array());

        return parent::getStringStatus();
    }

}
