<?php

namespace Proxies\__CG__\Flair\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Organisme extends \Flair\UserBundle\Entity\Organisme implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'nom', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'siret', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'ape', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'rna', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'adresse', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'codePostal', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'complementAdresse', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'ville', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'telephone', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'mobile', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'categorie', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'autreCategorie', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'prenomContact', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'nomContact', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'consultations', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'prestataires', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'entreprise', 'id', 'email', 'salt', 'password', 'roles', 'dateInscription', 'token', 'emailValide', 'resetToken', 'resetDate');
        }

        return array('__isInitialized__', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'nom', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'siret', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'ape', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'rna', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'adresse', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'codePostal', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'complementAdresse', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'ville', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'telephone', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'mobile', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'categorie', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'autreCategorie', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'prenomContact', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'nomContact', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'consultations', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'prestataires', '' . "\0" . 'Flair\\UserBundle\\Entity\\Organisme' . "\0" . 'entreprise', 'id', 'email', 'salt', 'password', 'roles', 'dateInscription', 'token', 'emailValide', 'resetToken', 'resetDate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Organisme $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie($categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', array($categorie));

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', array());

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal($codePostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', array($codePostal));

        return parent::setCodePostal($codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', array());

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', array($mobile));

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', array());

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomContact($nomContact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomContact', array($nomContact));

        return parent::setNomContact($nomContact);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomContact', array());

        return parent::getNomContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomContact($prenomContact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomContact', array($prenomContact));

        return parent::setPrenomContact($prenomContact);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomContact', array());

        return parent::getPrenomContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiret($siret)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiret', array($siret));

        return parent::setSiret($siret);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiret()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiret', array());

        return parent::getSiret();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiren($siren)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiren', array($siren));

        return parent::setSiren($siren);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiren', array());

        return parent::getSiren();
    }

    /**
     * {@inheritDoc}
     */
    public function setApe($ape)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApe', array($ape));

        return parent::setApe($ape);
    }

    /**
     * {@inheritDoc}
     */
    public function getApe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApe', array());

        return parent::getApe();
    }

    /**
     * {@inheritDoc}
     */
    public function setRna($rna)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRna', array($rna));

        return parent::setRna($rna);
    }

    /**
     * {@inheritDoc}
     */
    public function getRna()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRna', array());

        return parent::getRna();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', array($ville));

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', array());

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomComplet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomComplet', array());

        return parent::getNomComplet();
    }

    /**
     * {@inheritDoc}
     */
    public function setConsultations($consultations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsultations', array($consultations));

        return parent::setConsultations($consultations);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsultations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsultations', array());

        return parent::getConsultations();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrestataires($prestataires)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrestataires', array($prestataires));

        return parent::setPrestataires($prestataires);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrestataires()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrestataires', array());

        return parent::getPrestataires();
    }

    /**
     * {@inheritDoc}
     */
    public function getComplementAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplementAdresse', array());

        return parent::getComplementAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplementAdresse($complementAdresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplementAdresse', array($complementAdresse));

        return parent::setComplementAdresse($complementAdresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutreCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutreCategorie', array());

        return parent::getAutreCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutreCategorie($autreCategorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutreCategorie', array($autreCategorie));

        return parent::setAutreCategorie($autreCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompletion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompletion', array());

        return parent::getCompletion();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntreprise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntreprise', array());

        return parent::getEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntreprise(\Flair\UserBundle\Entity\Entreprise $entreprise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntreprise', array($entreprise));

        return parent::setEntreprise($entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function hasRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRole', array($role));

        return parent::hasRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', array($roles));

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function addRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', array($role));

        return parent::addRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', array($role));

        return parent::removeRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', array($serialized));

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array($salt));

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', array());

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', array());

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', array());

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', array());

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateInscription($dateInscription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateInscription', array($dateInscription));

        return parent::setDateInscription($dateInscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateInscription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateInscription', array());

        return parent::getDateInscription();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailValide($emailValide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailValide', array($emailValide));

        return parent::setEmailValide($emailValide);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailValide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailValide', array());

        return parent::getEmailValide();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', array($token));

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', array());

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setResetDate($resetDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResetDate', array($resetDate));

        return parent::setResetDate($resetDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getResetDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResetDate', array());

        return parent::getResetDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setResetToken($resetToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResetToken', array($resetToken));

        return parent::setResetToken($resetToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getResetToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResetToken', array());

        return parent::getResetToken();
    }

}
