services:
    invitation_form_type:
        class: Flair\UserBundle\Form\Type\InvitationFormType
        arguments: ['@security.context']
        tags:
            - {name: form.type, alias: invitation_form_type}
