security:
    encoders:
        Flair\UserBundle\Entity\AbstractUtilisateur: sha512

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_CONSULTANT:    ROLE_USER
        ROLE_GESTIONNAIRE:  ROLE_CONSULTANT
        ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_SONATA_ADMIN]

    providers:
        database:
            entity: { class: FlairUserBundle:AbstractUtilisateur, property: email}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        application:
            provider: database
            pattern: ^/
            anonymous: true
            access_denied_url: /
            form_login:
                default_target_path: /mon-compte
                post_only: true
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /login


    access_control:
        # Admin
        #- { path: ^/admin, role: ROLE_SUPER_ADMIN}

        # Partage
        # ~~~~~~~
        - { path: ^/mon-compte, role: ROLE_USER}
        - { path: ^/mes-services, role: ROLE_USER}
        - { path: ^/mes-invitations, role: ROLE_USER}

        # Organismes
        # ~~~~~~~~~~
        - { path: ^/creation-demande/etape-1, role: ROLE_ORGANISME }
        - { path: ^/creation-demande/etape-2, role: ROLE_ORGANISME }
        - { path: ^/creation-demande/etape-3, role: ROLE_ORGANISME }

        - { path: ^/mes-consultations$, role: ROLE_ORGANISME }
        - { path: ^/mes-prestataires$, role: ROLE_ORGANISME }

        - { path: ^/demandes/, role: ROLE_ORGANISME }

        # Prestataires
        # ~~~~~~~~~~~~
        - { path: ^/mes-propositions, role: ROLE_PRESTATAIRE }

        # Admin
        # ~~~~~
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
