<?php

namespace Proxies\__CG__\Flair\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reponse extends \Flair\CoreBundle\Entity\Reponse implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'id', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'consultation', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'prestataire', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'dateReponse', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'periodeDebut', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'dateDebut', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'periodeLivraison', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'dateLivraison', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'certificationRequise', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'certification', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'montantHt', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'montantTtc', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'hasDocuments', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'devisDocument', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'documents', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'lignesDevis', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'questions', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'statut', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'reponse');
        }

        return array('__isInitialized__', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'id', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'consultation', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'prestataire', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'dateReponse', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'periodeDebut', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'dateDebut', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'periodeLivraison', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'dateLivraison', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'certificationRequise', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'certification', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'montantHt', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'montantTtc', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'hasDocuments', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'devisDocument', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'documents', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'lignesDevis', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'questions', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'statut', '' . "\0" . 'Flair\\CoreBundle\\Entity\\Reponse' . "\0" . 'reponse');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Reponse $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function hasUnansweredQuestions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasUnansweredQuestions', array());

        return parent::hasUnansweredQuestions();
    }

    /**
     * {@inheritDoc}
     */
    public function addLignesDevi(\Flair\CoreBundle\Entity\LigneDevis $ligne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLignesDevi', array($ligne));

        return parent::addLignesDevi($ligne);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLignesDevi(\Flair\CoreBundle\Entity\LigneDevis $ligne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLignesDevi', array($ligne));

        return parent::removeLignesDevi($ligne);
    }

    /**
     * {@inheritDoc}
     */
    public function setConsultation($consultation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsultation', array($consultation));

        return parent::setConsultation($consultation);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsultation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsultation', array());

        return parent::getConsultation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrestataire($prestataire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrestataire', array($prestataire));

        return parent::setPrestataire($prestataire);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrestataire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrestataire', array());

        return parent::getPrestataire();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', array($statut));

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', array());

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateReponse($dateReponse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateReponse', array($dateReponse));

        return parent::setDateReponse($dateReponse);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateReponse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateReponse', array());

        return parent::getDateReponse();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebut($dateDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebut', array($dateDebut));

        return parent::setDateDebut($dateDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebut', array());

        return parent::getDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodeDebut($periodeDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodeDebut', array($periodeDebut));

        return parent::setPeriodeDebut($periodeDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodeDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodeDebut', array());

        return parent::getPeriodeDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodeLivraison($periodeLivraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodeLivraison', array($periodeLivraison));

        return parent::setPeriodeLivraison($periodeLivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodeLivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodeLivraison', array());

        return parent::getPeriodeLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateLivraison($dateLivraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateLivraison', array($dateLivraison));

        return parent::setDateLivraison($dateLivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateLivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateLivraison', array());

        return parent::getDateLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantHt($montantHt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantHt', array($montantHt));

        return parent::setMontantHt($montantHt);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantHt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantHt', array());

        return parent::getMontantHt();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantTtc($montantTtc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantTtc', array($montantTtc));

        return parent::setMontantTtc($montantTtc);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantTtc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantTtc', array());

        return parent::getMontantTtc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDevisDocument($devisDocument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDevisDocument', array($devisDocument));

        return parent::setDevisDocument($devisDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function getDevisDocument()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevisDocument', array());

        return parent::getDevisDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocuments($documents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocuments', array($documents));

        return parent::setDocuments($documents);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocuments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocuments', array());

        return parent::getDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function setHasDocuments($hasDocuments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasDocuments', array($hasDocuments));

        return parent::setHasDocuments($hasDocuments);
    }

    /**
     * {@inheritDoc}
     */
    public function getHasDocuments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasDocuments', array());

        return parent::getHasDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuestions($questions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuestions', array($questions));

        return parent::setQuestions($questions);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuestions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuestions', array());

        return parent::getQuestions();
    }

    /**
     * {@inheritDoc}
     */
    public function setLignesDevis($lignesDevis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLignesDevis', array($lignesDevis));

        return parent::setLignesDevis($lignesDevis);
    }

    /**
     * {@inheritDoc}
     */
    public function getLignesDevis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLignesDevis', array());

        return parent::getLignesDevis();
    }

    /**
     * {@inheritDoc}
     */
    public function setCertification($certification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCertification', array($certification));

        return parent::setCertification($certification);
    }

    /**
     * {@inheritDoc}
     */
    public function getCertification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCertification', array());

        return parent::getCertification();
    }

    /**
     * {@inheritDoc}
     */
    public function setCertificationRequise($certificationRequise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCertificationRequise', array($certificationRequise));

        return parent::setCertificationRequise($certificationRequise);
    }

    /**
     * {@inheritDoc}
     */
    public function getCertificationRequise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCertificationRequise', array());

        return parent::getCertificationRequise();
    }

    /**
     * {@inheritDoc}
     */
    public function setReponse($reponse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReponse', array($reponse));

        return parent::setReponse($reponse);
    }

    /**
     * {@inheritDoc}
     */
    public function getReponse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReponse', array());

        return parent::getReponse();
    }

    /**
     * {@inheritDoc}
     */
    public function getStringStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStringStatus', array());

        return parent::getStringStatus();
    }

}
